### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by DifferentialityDevelopment** [hmlendea/duolingo-desktop#2]
Hey there :) 

Just thought I'd mention this here,
I wanted to get Duolingo setup in an electronjs app and I found your repo, building it was easy enough but once I tried to login with Google I ran into issues, the webview doesn't work with the Google Auth and nothing happens when you try to login.

I updated electronjs dependency to the latest version, and instead loaded up Duolingo directly, I also disabled the code that intercepts the new window popup and instead of logging in using Google, which for some reason would still not allow the Electronjs browser, I logged in using facebook.

Now the duolingo desktop app is running perfectly.

**Comment by hmlendea** [comment]
I will give this a look for the next update, but unfortunately it's not going to be a priority for now.
