### ISSUE TITLE
no microphone access

### ISSUE THREAD

**Issue by amigo-de-cass** [hmlendea/duolingo-desktop#29]
hi
I'm using 
Ubuntu 21.04 64 bit
5.11.0-37-generic kernel
stable/latest 2.0.6 installed

from within the desktop-app I don't have an option to include speaking exercises, I believe this is due to Duolingo having migrated their code and now requires the google Web Speech API (I failed to get it to work in Firefox so I have has to download Chrome)

from Chrome
![image](https://user-images.githubusercontent.com/91839527/135762099-47d5bf90-f470-4dca-b7b9-f68725c83470.png)

from duolingo-app
![image](https://user-images.githubusercontent.com/91839527/135762140-a27b1f46-cf8c-4335-811a-429cfba26053.png)

great app by the way.  Thank you for your hard work

**Comment by hmlendea** [comment]
Hi,

Are you using the Duolingo website or the `duolingo-desktop` application for desktop Linux?

This repo is for the latter _(duolingo-desktop)_

**Comment by amigo-de-cass** [comment]
I am using the desktop app

**Comment by hmlendea** [comment]
Which version of the app are you using? Is it the regular binary or snap, etc?

**Comment by hmlendea** [comment]
The problem has been identified and will be fixed shortly.
