### ISSUE TITLE
Microphone Access Problem

### ISSUE THREAD

**Issue by junapu** [hmlendea/duolingo-desktop#32]
The app can't access to my microphone, the error shown is "Duolingo is having trouble accessing your microphone. This could be due to an existing Chrome bug. To fix it, please try restarting Chrome". I was using Brave as browser, then I've noticed that the speaking option was only available in Chrome, so I set Chrome as default and enable the speaking exercises. Then, I uninstall the app and install it again. But the problem is still there. I hope someone could help me!

Certainly it is a great app. Congrats!

Edit: I was using snap version. I've tried with .deb, but now the issue is that when I click the "Click to Speak" buttom it takes it wrong automaticly.

**Comment by hmlendea** [comment]
I think I might have found the issue and I will make a new version shortly, which will hopefully fix it one and for all (for the snap version).
