### ISSUE TITLE
Has No Icon in KDE Linux Desktop Environments

### ISSUE THREAD

**Issue by ThisNekoGuy** [hmlendea/duolingo-desktop#6]
![image](https://user-images.githubusercontent.com/28468662/85099835-1b6c2500-b1c4-11ea-8efd-6ffccf76a6d5.png)

I installed the app through the Manjaro AUR (it compiles and installs things for you) and, while not a major issue, it doesn't have an icon for it and won't allow for one to be set.

(Also, a side note, I can't find the dark mode setting anywhere.)

**Comment by hmlendea** [comment]
Hello,

I have no experience at all with KDE unfortunately.
Could you provide some guidance on how the entries in the .desktop files should look like for KDE, if you know?

Also, the dark mode was an old feature in v1 which was dropped when this (dead for a long time) project was picked up again and updated to be in a working state again in v2.
I hope to bring dark mode back, but it wasn't easy (for me) to do it while updating the app, so it was delayed.
When I have some time to bring new (or in this case old) features into this app, I'm definetely trying dark mode first.
However, I forgot to update the readme file, so this is where the confusion comes from. So thanks for telling me.

**Comment by ThisNekoGuy** [comment]
Using the the AUR-compiled version of Godot-mono (Godot is an open source game development engine), it produced its .desktop file like this:

![image](https://user-images.githubusercontent.com/28468662/85173537-139a9800-b239-11ea-9698-7eabeea74e73.png)

Another example from the Dolphin GameCube emulator:

![image](https://user-images.githubusercontent.com/28468662/85173694-6f652100-b239-11ea-84cf-5d5ed6c9a81d.png)

**Comment by hmlendea** [comment]
Doesn't look too different from the values used in GNOME.

Well, it means that there's an issue with the desktop file provided by that AUR package, since this repo doesn't provide a desktop file of its own.

In any case, I'll upload a .desktop file to this repository so that the packages for different distros won't have to do it themselves, and to have them all aligned with the same desktop file values.
